config/routes.rb
Rails.application.routes.draw do

  resources :answers
  resources :questions
  root 'home#index'

  get '/about' => 'home#about'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    question = Question.find(params[:answer][:question_id])
    answer = question.answers.create(answer_params)
    MainMailer.notify_question_author(answer).deliver_later
    session[:current_user_email] = answer_params[:email]
    redirect_to question
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, :email, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc)
  end

  def about
  end

  def temp
    redirect_to root_path
  end

  def question
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :desc)
  end

  def create
    Question.create(question_params)
    session[:current_user_email] = question_params[:email]
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:email, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_email
    session[:current_user_email]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New answer</h4>
      </div>

      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
        <input type="hidden" name="answer[question_id]" value="<%= @question.id %>" />
        <div class="modal-body">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="answer[email]" value="<%= current_user_email %>" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="answer" class="col-sm-2 control-label">Answer</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="answer[body]" id="inputAnswer" required></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">History of the Universe</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="navbar-text"><%= current_user_email %></div>
        </li>
        <li><form><a href="#"  class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-question-modal">Ask a question</a></form></li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New answer</h4>
      </div>

      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
        <div class="modal-body">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="answer" class="col-sm-2 control-label">Answer</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="answer_body" id="inputAnswer"  required></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New quesion</h4>
      </div>

      <%= form_for :question, url: '/questions', html: { class: 'form-horizontal' } do %>
        <div class="modal-body">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="question[email]" value="<%= current_user_email %>" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="question" class="col-sm-2 control-label">Question</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="question[body]" id="inputQuestion"  placeholder="What would you like to know" required></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<% @questions.each do |q| %>
  <div class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object" src="http://thenextweb.com/wp-content/blogs.dir/1/files/2010/03/gravatar.jpg" alt="Not found">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= q.email %> asked:</h4>
      <p><%= time_ago_in_words q.created_at %> ago</p>
      <p><%= q.body %></p>
      <div>
        <a href="<%= question_path(q) %>" class="btn btn-success btn-xs">View Answers</a>
      </div>
    </div>
  </div>
<% end %>
<% if @questions.empty? %>
  <div class="alert alert-info">There are no questions yet.</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HU</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'home/navbar' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'home/new_question_form' %>

</body>
</html>

app/views/questions/show.html.erb
<div class="lead well">
  <div class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object" src="http://thenextweb.com/wp-content/blogs.dir/1/files/2010/03/gravatar.jpg" alt="Not found">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= @question.email %></h4>
      <p><%= @question.body %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2">

    <% if @answers.empty? %>
      <div class="alert alert-info">There are no answers yet.</div>
    <% end %>
    <div>
      <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</a>
    </div>

    <%= render 'answers/new_answer_form' %>

    <% @answers.each do |answer| %>
      <div class="media">
        <div class="media-left">
          <a href="#">
            <img class="media-object" src="http://thenextweb.com/wp-content/blogs.dir/1/files/2010/03/gravatar.jpg" alt="Not found">
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= answer.email %></h4>
          <%= time_ago_in_words answer.created_at %> ago
          <p/>
          <%= answer.body %>
        </div>
      </div>
    <% end %>

  </div>
</div>